# Generated by Django 5.2.16 on 2026-07-19 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iclock', '0001_initial'),
        ('mclock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location_verified', models.BooleanField(default=False, help_text='True kalau koordinat GPS yang dikirim berada di dalam polygon salah satu MobilePool.')),
                ('face_verified', models.BooleanField(default=False, help_text='True kalau wajah yang di-capture saat check-in/out cocok dengan FaceProfile user (face_recognition). Selalu False utk Check/Meal (tidak pakai verifikasi wajah, pakai QR).')),
                ('check_type', models.CharField(choices=[('IN', 'Check-in'), ('OUT', 'Check-out'), ('MEAL', 'Check/Meal')], default='IN', max_length=4)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Koordinat GPS yang DIKIRIM user saat check-in/out (utk audit).', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_meters', models.FloatField(blank=True, help_text='Jarak (meter) ke PoolID yang cocok. Kosong kalau tidak ada pool yang cocok sama sekali.', null=True)),
                ('face_distance', models.FloatField(blank=True, help_text='Jarak Euclidean antara wajah check-in ini dgn FaceProfile terdaftar (dari face_recognition.face_distance) -- makin kecil makin mirip, 0 = identik. Utk audit.', null=True)),
                ('qr_content', models.CharField(blank=True, help_text='Isi QR code yang di-scan (khusus Check/Meal) -- utk audit, lihat settings.QRDEVICE.', max_length=100, null=True)),
                ('Function', models.CharField(blank=True, help_text="Format '<kode fungsi>-<PoolID>' (mirip iclock.transaction.Function), mis. '89-101' utk KARYAWAN di PoolID 101, 'X-101' utk Check/Meal di PoolID yang sama. Kode fungsi merujuk ke settings.DEVICEFUNCTION.", max_length=20, null=True)),
                ('PoolID', models.ForeignKey(blank=True, help_text='Pool/lokasi yang cocok dengan geofence saat check-in/out ini (kosong kalau tidak ada yang cocok).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='mclock.mobilepool')),
                ('user', models.ForeignKey(help_text='User (accounts) yang melakukan check-in/out ini.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Log',
                'db_table': 'mattendance_log',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.JSONField(help_text='128-dimension face encoding dari face_recognition, disimpan sebagai list of float (JSON array).')),
                ('is_locked', models.BooleanField(default=False, help_text='Otomatis diset True begitu 1 kali enrollment berhasil -- "pengambilan wajah hanya dilakukan sekali". Selama True, user TIDAK BISA mendaftar ulang sendiri (harus hubungi admin). Admin bisa buka kunci (set False) lewat halaman Face Profile kalau employee legitimately butuh enroll ulang (mis. wajah berubah signifikan).', verbose_name='Terkunci (ReadOnly)')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(help_text='1 employee cuma boleh punya 1 profil wajah terdaftar (berlaku bersama utk semua akun User yang ter-link ke employee ini).', on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to='iclock.employee')),
            ],
            options={
                'verbose_name': 'Face Profile',
                'verbose_name_plural': 'Face Profiles',
                'db_table': 'mattendance_face_profile',
                'managed': True,
            },
        ),
    ]
