# Generated by Django 5.0.14 on 2026-08-03 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iclock', '0011_alter_featurepermission_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('karyawan', 'Karyawan'), ('driver', 'Driver'), ('visitor', 'Visitor'), ('bhl', 'BHL (Buruh Harian Lepas)')], max_length=20, verbose_name='Jenis Kartu')),
                ('name', models.CharField(help_text='Label pengenal, mis. "Karyawan - Biru 2026"', max_length=100, verbose_name='Nama Template')),
                ('background_image', models.ImageField(upload_to='idcard/templates/', verbose_name='Gambar Background')),
                ('is_active', models.BooleanField(default=True, help_text='Kalau nonaktif, template ini tidak muncul sbg pilihan saat generate kartu baru.', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
            ],
            options={
                'verbose_name': 'Template ID Card',
                'verbose_name_plural': 'Template ID Card',
                'ordering': ['card_type', '-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visitor', 'Visitor'), ('bhl', 'BHL (Buruh Harian Lepas)')], max_length=20, verbose_name='Jenis Kartu')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='No. KTP/Identitas')),
                ('company', models.CharField(blank=True, help_text='Utk Visitor: perusahaan asal tamu.', max_length=150, verbose_name='Perusahaan/Asal')),
                ('purpose', models.CharField(blank=True, help_text='Utk Visitor: tujuan kunjungan/nama yang dituju.', max_length=255, verbose_name='Keperluan/Sponsor')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='idcard/holder_photos/', verbose_name='Foto')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Berlaku Dari')),
                ('valid_until', models.DateField(blank=True, help_text='Kosongkan kalau tidak ada batas waktu.', null=True, verbose_name='Berlaku Sampai')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Data Pemegang Kartu (Visitor/BHL)',
                'verbose_name_plural': 'Data Pemegang Kartu (Visitor/BHL)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('karyawan', 'Karyawan'), ('driver', 'Driver'), ('visitor', 'Visitor'), ('bhl', 'BHL (Buruh Harian Lepas)')], max_length=20, verbose_name='Jenis Kartu')),
                ('photo_source', models.CharField(choices=[('ftp', 'Ambil dari FTP'), ('shoot', 'Shoot Langsung'), ('upload', 'Upload File')], max_length=10, verbose_name='Sumber Foto')),
                ('photo', models.ImageField(help_text='Foto MENTAH sebelum di-composite ke template (utk arsip/generate ulang).', upload_to='idcard/source_photos/', verbose_name='Foto Sumber')),
                ('card_image', models.ImageField(help_text='Gambar akhir siap cetak.', upload_to='idcard/generated/', verbose_name='Hasil Kartu')),
                ('status', models.CharField(choices=[('belum_cetak', 'Belum Cetak'), ('sudah_cetak', 'Sudah Cetak'), ('hilang', 'Hilang'), ('cetak_ulang', 'Cetak Ulang')], default='belum_cetak', max_length=20, verbose_name='Status')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Digenerate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards', to='iclock.employee', verbose_name='Karyawan')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards', to='idcard.idcardholder', verbose_name='Pemegang Kartu')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_cards', to='idcard.idcardtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'ID Card',
                'verbose_name_plural': 'ID Card',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum_cetak', 'Belum Cetak'), ('sudah_cetak', 'Sudah Cetak'), ('hilang', 'Hilang'), ('cetak_ulang', 'Cetak Ulang')], max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='idcard.idcard', verbose_name='Kartu')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dicatat Oleh')),
            ],
            options={
                'verbose_name': 'Log Status ID Card',
                'verbose_name_plural': 'Log Status ID Card',
                'ordering': ['-changed_at'],
            },
        ),
    ]
