# Generated by Django 5.2.16 on 2026-07-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetmgmtRouterDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('dhcp', 'DHCP Lease'), ('fwfilter', 'Firewall Filter')], max_length=30, unique=True, verbose_name='Halaman')),
                ('router_ip', models.CharField(max_length=20, verbose_name='IP Router Default')),
            ],
            options={
                'verbose_name': 'Router Default (NetMgmt)',
                'verbose_name_plural': 'Router Default (NetMgmt)',
            },
        ),
    ]
