# Generated by Django 5.0.14 on 2026-07-31 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITInfraCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nama Kategori')),
            ],
            options={
                'verbose_name': 'Kategori Data IT-Infra',
                'verbose_name_plural': 'Kategori Data IT-Infra',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ITInfraEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label pengenal entry ini, mis. "Internet Kantor Pusat - Biznet"', max_length=150, verbose_name='Nama')),
                ('data_encrypted', models.TextField(blank=True, editable=False, verbose_name='Data (terenkripsi)')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='netmgmt.itinfracategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Data IT-Infra',
                'verbose_name_plural': 'Data IT-Infra',
                'ordering': ['category__name', 'name'],
            },
        ),
    ]
