# Generated by Django 5.0.14 on 2026-08-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmgmt', '0002_itinfracategory_itinfraentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinfraentry',
            name='is_staff_only',
            field=models.BooleanField(default=False, help_text='Kalau dicentang, entry ini HANYA bisa dilihat staff/admin -- tersembunyi dari user portal non-staff meski mereka punya izin akses fitur ini.', verbose_name='Staff Only'),
        ),
    ]
