# Generated by Django 5.2.16 on 2026-08-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmgmt', '0003_itinfraentry_is_staff_only'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itinfraentry',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_name_category'),
        ),
    ]
