# Generated by Django 5.2.16 on 2026-07-19 04:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('auth_source', models.CharField(choices=[('local', 'Local'), ('ldap', 'LDAP'), ('mobile_pin', 'Mobile (PIN Employee)')], default='local', help_text='Sumber identitas user: dibuat manual (local), sinkron dari LDAP, atau otomatis dari login mobile via PIN.', max_length=10)),
                ('must_change_password', models.BooleanField(default=False, help_text='True kalau password baru saja di-reset admin / dibuat baru, wajib ganti.')),
                ('is_mobile_only', models.BooleanField(default=False, help_text='True kalau akun ini dibuat OTOMATIS lewat login Mobile Attendance via PIN Employee (accounts/mobile_backend.py), BUKAN akun biasa yang dibuat admin/LDAP. Akses dibatasi HANYA ke check-in/out/meal & enrollment wajah -- lihat accounts/middleware.py.')),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_user',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
