# Generated by Django 5.2.16 on 2026-07-19 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('iclock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EmpID',
            field=models.ForeignKey(blank=True, help_text='Link opsional ke data Employee (iclock) yang berkaitan dengan akun user ini.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='iclock.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
