# Generated by Django 5.2.16 on 2026-07-19 04:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_transfer_finger', 'Bisa melakukan Transfer Data Finger'), ('can_view_attendance_recap', 'Bisa melihat Rekap Absensi (Attendance Recap)')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('DeptID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Pool ID')),
                ('DeptName', models.CharField(max_length=20, verbose_name='Pool Name')),
                ('NetID', models.IntegerField(default=0, verbose_name='Net ID')),
                ('DeptRouter', models.CharField(default='192.168.XXX.254', max_length=20, verbose_name='Router')),
                ('DeptSubnet', models.CharField(default='192.168.XXX.0/24', max_length=20, verbose_name='Subnet')),
            ],
            options={
                'verbose_name': 'Pool',
                'verbose_name_plural': 'Pool',
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='iclock',
            fields=[
                ('SN', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('Alias', models.CharField(max_length=20, verbose_name='Device Alias')),
                ('IPAddress', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP Address')),
                ('MAC', models.CharField(blank=True, max_length=20, null=True, verbose_name='MAC Address')),
                ('TZAdj', models.SmallIntegerField(blank=True, default=8, null=True, verbose_name='Timezone Offset')),
                ('Function', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Function')),
                ('DeviceName', models.CharField(blank=True, editable=False, max_length=30, null=True, verbose_name='Device Name')),
                ('State', models.IntegerField(default=1, editable=False)),
                ('LastActivity', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last Activity')),
                ('PushVersion', models.CharField(blank=True, default='0.0', editable=False, max_length=10, null=True)),
                ('TransInterval', models.IntegerField(default=1, editable=False)),
                ('UpdateDB', models.CharField(default='1111111100', editable=False, max_length=10)),
                ('LockFunOn', models.SmallIntegerField(db_column='AccFun', default=0, editable=False)),
                ('DelTag', models.SmallIntegerField(default=0, editable=False)),
                ('DeptID', models.ForeignKey(blank=True, db_column='DeptID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iclock.department', verbose_name='Pool')),
            ],
            options={
                'verbose_name': 'Active Device',
                'verbose_name_plural': 'Active Devices',
                'db_table': 'iclock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('PIN', models.CharField(db_column='badgenumber', max_length=20, verbose_name='PIN')),
                ('EName', models.CharField(blank=True, db_column='name', default=' ', max_length=40, null=True, verbose_name='Employee Name')),
                ('Password', models.CharField(blank=True, max_length=20, null=True, verbose_name='Password')),
                ('Card', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Card')),
                ('Privilege', models.IntegerField(blank=True, choices=[(0, 'Normal'), (2, 'Registrar'), (6, 'Administrator'), (14, 'Supervisor')], null=True, verbose_name='Privilege')),
                ('AccGroup', models.IntegerField(blank=True, null=True, verbose_name='Access Group')),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True, verbose_name='Gender')),
                ('Title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Title')),
                ('Tele', models.CharField(blank=True, db_column='ophone', max_length=20, null=True, verbose_name='Office Phone')),
                ('Mobile', models.CharField(blank=True, db_column='pager', max_length=20, null=True, verbose_name='Mobile')),
                ('DelTag', models.SmallIntegerField(default=0, editable=False)),
                ('UTime', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Refresh Time')),
                ('mpassword', models.CharField(blank=True, help_text='Password (di-hash) login Mobile Attendance via PIN. Kosong = belum pernah diganti dari default.', max_length=255, null=True)),
                ('DeptID', models.ForeignKey(blank=True, db_column='defaultdeptid', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='iclock.department', verbose_name='Pool')),
                ('SN', models.ForeignKey(blank=True, db_column='SN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iclock.iclock', verbose_name='Registration Device')),
            ],
            options={
                'verbose_name': 'Device User',
                'verbose_name_plural': 'Device Users',
                'db_table': 'userinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='devlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OP', models.CharField(default='TRANSACT', max_length=8, verbose_name='Data Type')),
                ('Object', models.CharField(blank=True, max_length=20, null=True, verbose_name='Object')),
                ('Cnt', models.IntegerField(blank=True, default=1, verbose_name='Record Count')),
                ('ECnt', models.IntegerField(blank=True, default=0, verbose_name='Error Count')),
                ('OpTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload Time')),
                ('SN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iclock.iclock', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Device Log',
                'verbose_name_plural': 'Device Logs',
                'db_table': 'devlog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='devcmds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CmdContent', models.TextField(max_length=2048, verbose_name='Command Content')),
                ('CmdCommitTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submit Time')),
                ('CmdTransTime', models.DateTimeField(blank=True, null=True, verbose_name='Transfer Time')),
                ('CmdOverTime', models.DateTimeField(blank=True, null=True, verbose_name='Return Time')),
                ('CmdReturn', models.IntegerField(blank=True, null=True, verbose_name='Return Value')),
                ('User', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
                ('SN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iclock.iclock', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Device Command',
                'verbose_name_plural': 'Device Commands',
                'db_table': 'devcmds',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=20, unique=True, verbose_name='Serial Number')),
                ('DeviceName', models.CharField(blank=True, max_length=30, null=True, verbose_name='Device Name')),
                ('Function', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Function')),
                ('IPAddress', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP Address')),
                ('MAC', models.CharField(blank=True, max_length=20, null=True, verbose_name='MAC Address')),
                ('IPRouter', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP Router')),
                ('LastActivity', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last Activity')),
                ('DeptID', models.ForeignKey(blank=True, db_column='DeptID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='iclock.department', verbose_name='Pool')),
            ],
            options={
                'verbose_name': 'Registered Device',
                'verbose_name_plural': 'Registered Devices',
                'db_table': 'iclock_registereddevice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='fptemp',
            fields=[
                ('id', models.AutoField(db_column='templateid', primary_key=True, serialize=False)),
                ('Template', models.TextField(verbose_name='Template')),
                ('FingerID', models.SmallIntegerField(choices=[(0, 'Right Index Finger'), (1, 'Left Index Finger'), (2, 'Right Middle Finger'), (3, 'Left Middle Finger'), (4, 'Right Thumb'), (5, 'Left Thumb'), (6, 'Right Ring Finger'), (7, 'Left Ring Finger'), (8, 'Right Little Finger'), (9, 'Left Little Finger')], default=0, verbose_name='Finger')),
                ('Valid', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1, verbose_name='Valid')),
                ('DelTag', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Deleted')),
                ('UTime', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Refresh Time')),
                ('UserID', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='iclock.employee', verbose_name='Employee')),
                ('SN', models.ForeignKey(blank=True, db_column='SN', null=True, on_delete=django.db.models.deletion.CASCADE, to='iclock.iclock', verbose_name='Registration Device')),
            ],
            options={
                'verbose_name': 'Fingerprint Template',
                'verbose_name_plural': 'Fingerprint Templates',
                'db_table': 'template',
                'managed': True,
                'unique_together': {('UserID', 'FingerID')},
            },
        ),
        migrations.CreateModel(
            name='oplog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.IntegerField(default=0, verbose_name='Device Administrator')),
                ('OP', models.SmallIntegerField(default=0, verbose_name='Operation Code')),
                ('OPTime', models.DateTimeField(verbose_name='Time')),
                ('Object', models.IntegerField(blank=True, null=True, verbose_name='Object')),
                ('Param1', models.IntegerField(blank=True, null=True, verbose_name='Parameter 1')),
                ('Param2', models.IntegerField(blank=True, null=True, verbose_name='Parameter 2')),
                ('Param3', models.IntegerField(blank=True, null=True, verbose_name='Parameter 3')),
                ('SN', models.ForeignKey(blank=True, db_column='SN', null=True, on_delete=django.db.models.deletion.CASCADE, to='iclock.iclock', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Device Operation Log',
                'verbose_name_plural': 'Device Operation Logs',
                'db_table': 'iclock_oplog',
                'managed': True,
                'unique_together': {('SN', 'OPTime')},
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TTime', models.DateTimeField(db_column='checktime', verbose_name='Time')),
                ('State', models.CharField(choices=[('0', 'Check in'), ('1', 'Check out'), ('2', 'Break out'), ('3', 'Break in'), ('4', 'Overtime in'), ('5', 'Overtime out'), ('8', 'Meal start'), ('9', 'Meal end')], db_column='checktype', default='0', max_length=1, verbose_name='State')),
                ('Verify', models.IntegerField(choices=[(0, 'Password'), (1, 'Fingerprint'), (2, 'Card'), (9, 'Other')], db_column='verifycode', default=0, verbose_name='Verification')),
                ('WorkCode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Work Code')),
                ('Reserved', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reserved')),
                ('Function', models.CharField(blank=True, max_length=20, null=True, verbose_name='Function')),
                ('SN', models.ForeignKey(blank=True, db_column='SN', null=True, on_delete=django.db.models.deletion.CASCADE, to='iclock.iclock', verbose_name='Device')),
                ('UserID', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='iclock.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'checkinout',
                'managed': True,
                'unique_together': {('UserID', 'TTime')},
            },
        ),
    ]
