# Generated by Django 5.2.16 on 2026-07-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iclock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iclock',
            name='Delay',
            field=models.IntegerField(default=30, help_text='Detik jeda antar koneksi device ke server dalam kondisi normal.', verbose_name='Delay'),
        ),
        migrations.AddField(
            model_name='iclock',
            name='Encrypt',
            field=models.BooleanField(default=False, help_text='Enkripsi data transfer device<->server. Lihat test/myrule.md poin 6 (masih tahap dicoba).', verbose_name='Encrypt'),
        ),
        migrations.AddField(
            model_name='iclock',
            name='ErrorDelay',
            field=models.IntegerField(default=60, help_text='Detik jeda reconnect device setelah koneksi ke server GAGAL.', verbose_name='Error Delay'),
        ),
        migrations.AddField(
            model_name='iclock',
            name='LogStamp',
            field=models.CharField(blank=True, default='0', help_text="Timestamp terakhir ATTLOG yang sudah diupload device ini (protokol lama: 'Stamp', baru: 'ATTLOGStamp').", max_length=20, null=True, verbose_name='Attendance Log Stamp'),
        ),
        migrations.AddField(
            model_name='iclock',
            name='OpLogStamp',
            field=models.CharField(blank=True, default='0', help_text="Timestamp terakhir OPERLOG (user/fingerprint/log) yang sudah diupload ('OpStamp'/'OPERLOGStamp').", max_length=20, null=True, verbose_name='Operation Log Stamp'),
        ),
        migrations.AddField(
            model_name='iclock',
            name='PhotoStamp',
            field=models.CharField(blank=True, default='0', help_text="Timestamp terakhir foto attendance yang sudah diupload ('PhotoStamp'/'ATTPHOTOStamp').", max_length=20, null=True, verbose_name='Photo Stamp'),
        ),
        migrations.AddField(
            model_name='iclock',
            name='Realtime',
            field=models.BooleanField(default=True, help_text='True: device upload data baru instan begitu ada. False: ikut jadwal TransTimes/TransInterval.', verbose_name='Realtime'),
        ),
        migrations.AddField(
            model_name='iclock',
            name='TransTimes',
            field=models.CharField(blank=True, default='00:00;14:05', help_text="Jadwal cek transfer data (format menit 24-jam, maks 10 slot dipisah ';'). Cuma dipakai kalau Realtime=0 & TransInterval=0.", max_length=50, null=True, verbose_name='Trans Times'),
        ),
        migrations.AddField(
            model_name='registereddevice',
            name='Alias',
            field=models.CharField(blank=True, help_text='Diisi otomatis dgn IP Address saat device auto-registrasi (Rule 2a) -- admin bisa ubah manual nanti.', max_length=20, null=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='iclock',
            name='TransInterval',
            field=models.IntegerField(default=1, help_text='Interval (menit) device mengecek & mengirim data baru ke server.', verbose_name='Trans Interval'),
        ),
        migrations.AlterField(
            model_name='iclock',
            name='UpdateDB',
            field=models.CharField(default='1111111100', editable=False, help_text="Ini field 'TransFlag' versi lama (nama kolom asli tabel ZKTeco) -- menentukan tipe data apa saja yang di-auto-upload device (attendance/operation log/foto/dst). Lihat resume protokol PUSH SDK bagian 3.1 utk arti tiap karakter.", max_length=10),
        ),
    ]
