# Generated by Django 5.2.16 on 2026-07-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iclock', '0002_iclock_delay_iclock_encrypt_iclock_errordelay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iclock',
            name='UpdateDB',
            field=models.CharField(default='1111111100', help_text="Ini field 'TransFlag' versi lama (nama kolom asli tabel ZKTeco) -- menentukan tipe data apa saja yang di-auto-upload device (attendance/operation log/foto/dst). Lihat resume protokol PUSH SDK bagian 3.1 utk arti tiap karakter.", max_length=10),
        ),
    ]
