# Generated by Django 5.2.16 on 2026-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iclock', '0003_alter_iclock_updatedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='LastVerify',
            field=models.IntegerField(blank=True, help_text="Kode Pool (PoolID mobile) terakhir -- cuma terisi kalau check-in terakhir lewat mobile (SN='ABSENDIGITAL01').", null=True, verbose_name='Last Mobile PoolID'),
        ),
    ]
