# Generated by Django 5.0.14 on 2026-08-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iclock', '0004_employee_lastverify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_transfer_finger', 'Bisa melakukan Transfer Data Finger'), ('can_view_attendance_recap', 'Bisa melihat Rekap Absensi - All (Attendance Recap)'), ('can_view_attendance_recap_kantin', 'Bisa melihat Rekap Absensi - Kantin'), ('can_view_attendance_recap_driver', 'Bisa melihat Rekap Absensi - Driver')]},
        ),
    ]
