# Generated by Django 5.2.16 on 2026-08-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iclock', '0005_alter_featurepermission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iclock',
            name='DeviceName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Device Name'),
        ),
    ]
