# Generated by Django 5.0.14 on 2026-08-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iclock', '0011_alter_featurepermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_transfer_finger', 'Bisa melakukan Transfer Data Finger'), ('can_view_attendance_recap', 'Bisa melihat Rekap Absensi - All (Attendance Recap)'), ('can_view_attendance_recap_kantin', 'Bisa melihat Rekap Absensi - Kantin'), ('can_view_attendance_recap_driver', 'Bisa melihat Rekap Absensi - Driver'), ('can_view_dhcp_lease', 'Bisa melihat DHCP Lease (Mikrotik)'), ('can_view_fwfilter', 'Bisa melihat & Grant Access Firewall Filter (Mikrotik)'), ('can_view_netwatch', 'Bisa melihat Netwatch (Mikrotik)'), ('can_view_ad_users', 'Bisa melihat & Kelola Users (Active Directory)'), ('can_view_ad_locked_users', 'Bisa melihat & Unlock Locked Users (Active Directory)'), ('can_view_ad_dns', 'Bisa melihat DNS (Active Directory)'), ('can_view_ad_groups', 'Bisa melihat Groups (Active Directory)'), ('can_view_zentyal_users', 'Bisa melihat & Kelola Users (Mail Server / Zentyal)'), ('can_view_zentyal_groups', 'Bisa melihat Groups (Mail Server / Zentyal)'), ('can_view_cloudflare', 'Bisa melihat & Kelola DNS Record - Tanpa Hapus (Cloudflare)'), ('can_view_itinfra', 'Bisa melihat Data IT-Infra (kecuali entry Staff Only)'), ('can_view_idcard', 'Bisa Generate & Kelola ID Card (semua jenis kartu)')]},
        ),
    ]
