# Generated by Django 5.2.16 on 2026-08-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iclock', '0013_alter_featurepermission_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transaction',
            name='TTime_Minute',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('UserID', 'State', 'TTime_Minute'), name='unique_user_state_minute'),
        ),
    ]
