# Generated by Django 5.2.16 on 2026-07-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePool',
            fields=[
                ('PoolID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('PoolCode', models.CharField(blank=True, max_length=50, null=True)),
                ('PoolName', models.CharField(blank=True, max_length=50, null=True)),
                ('Latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Radius', models.IntegerField(blank=True, null=True)),
                ('SyncedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mobile Pool',
                'verbose_name_plural': 'Mobile Pool',
                'db_table': 'mclock_mobile_pool',
                'ordering': ['PoolID'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PoolDeviceFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PoolID', models.CharField(help_text='PoolID dari MobilePool yang dipetakan function-nya.', max_length=5, unique=True)),
                ('function_type', models.CharField(choices=[('KANTIN', 'KANTIN'), ('BUKAN_KANTIN', 'Bukan KANTIN')], default='BUKAN_KANTIN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pool Device Function',
                'verbose_name_plural': 'Pool Device Function',
                'db_table': 'mclock_pool_device_function',
                'ordering': ['PoolID'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MobilePoolLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PoolID', models.CharField(max_length=5)),
                ('Urut', models.DecimalField(decimal_places=2, help_text='Urutan titik dalam polygon (menentukan urutan keliling).', max_digits=18)),
                ('Latitude', models.TextField(blank=True, null=True)),
                ('Longitude', models.TextField(blank=True, null=True)),
                ('SyncedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mobile Pool Location (Polygon)',
                'verbose_name_plural': 'Mobile Pool Location (Polygon)',
                'db_table': 'mclock_mobile_pool_loc',
                'ordering': ['PoolID', 'Urut'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('PoolID', 'Urut'), name='unique_poolid_urut')],
            },
        ),
    ]
